const Products = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    desc: "High-quality wireless headphones with noise cancellation.",
    price: 89,
    oldPrice: 120,
    rating: 4.8,
    image:
      "https://i.pinimg.com/736x/ec/ba/6a/ecba6aa4ade96e005e15bf495017f2f2.jpg",
  },
  {
    id: 2,
    name: "Smart Watch",
    category: "Electronics",
    desc: "Track your fitness and stay connected on the go.",
    price: 150,
    oldPrice: 200,
    rating: 4.7,
    image: "https://picsum.photos/300/300?random=2",
  },
  {
    id: 3,
    name: "Running Shoes",
    category: "Fashion",
    desc: "Comfortable and stylish shoes for everyday use.",
    price: 75,
    oldPrice: 95,
    rating: 4.5,
    image: "https://picsum.photos/300/300?random=3",
  },
  {
    id: 4,
    name: "Leather Backpack",
    category: "Fashion",
    desc: "Premium backpack with multiple storage compartments.",
    price: 60,
    oldPrice: 85,
    rating: 4.6,
    image: "https://picsum.photos/300/300?random=4",
  },
  {
    id: 5,
    name: "Gaming Mouse",
    category: "Electronics",
    desc: "RGB gaming mouse with adjustable DPI settings.",
    price: 35,
    oldPrice: 50,
    rating: 4.4,
    image: "https://picsum.photos/300/300?random=5",
  },
  {
    id: 6,
    name: "Office Chair",
    category: "Furniture",
    desc: "Ergonomic office chair for maximum comfort.",
    price: 180,
    oldPrice: 250,
    rating: 4.9,
    image: "https://picsum.photos/300/300?random=6",
  },
  {
    id: 7,
    name: "Bluetooth Speaker",
    category: "Electronics",
    desc: "Portable speaker with crystal-clear sound quality.",
    price: 55,
    oldPrice: 75,
    rating: 4.3,
    image: "https://picsum.photos/300/300?random=7",
  },
  {
    id: 8,
    name: "Sunglasses",
    category: "Fashion",
    desc: "Stylish UV-protected sunglasses for outdoor wear.",
    price: 30,
    oldPrice: 45,
    rating: 4.0,
    image: "https://picsum.photos/300/300?random=8",
  },
];

export default Products;
